### ISSUE TITLE
Some devices are being miscategorized

### ISSUE THREAD

**Issue by oNaiPs** [fyde/devices-metadata#10]
We had a report of a miscategorized device, which reports as `iPhone11,6` and is being translated as `iPhone XS Max China`.

However, there are other names for this same model:
https://everymac.com/ultimate-mac-lookup/?search_keywords=iPhone11,6

We should be using a more generic name for them (i found on this [list](https://gist.github.com/adamawolf/3048717) they call it "Global")

On another note, I noticed that `iPhone11,4` doesn't seem to be on the online list anymore.

**Comment by elyscape** [comment]
Per [this comment](https://gist.github.com/adamawolf/3048717#gistcomment-2847457), `iPhone11,4` has restore images available but, as far as anybody knows, was never a publicly released device.

**Comment by elyscape** [comment]
Per [everyi.com](https://everyi.com/by-identifier/ipod-iphone-ipad-specs-by-model-identifier.html), all variants of the `iPhone Xs Max` are `iPhone11,6`.
